

/*TABLO OLUŞTURMAK İÇİN CREATE TABLE KULLANIRIZ.*/
create table STUDENTS(

/*BURADA ID KISMINDA AUTO_INCREMENT KULLANDIK ÇÜNKÜ OTOMATİK ARTTIRIM YAPTIK.*/
ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
S_Name VARCHAR(50) NOT NULL,
S_Surname varchar(50) NOT NULL
);
/*BURADA VERİ EKLEMEK İÇİN INSERT INTO KULLANIYORUZ.*/
INSERT INTO STUDENTS(S_Name,S_Surname)
VALUES("KEMAL","TÜMER");

SELECT*FROM STUDENTS