use ETRADE4

--1-T�M KULLANICILARIN AD SOYADLARINI L�STELEME
SELECT NAMESURNAME FROM USERS

--2-ITEMS TABLOSUNDAK� T�M �R�NLER�N ADLARINI VE B�R�M F�YATLARINI L�STELEME
SELECT ITEMNAME ,UNITPRICE FROM ITEMS

--3-ORDERS TABLOSUNDAK� T�M S�PAR��LER�N TARH�LER�N� VE TOPLAM F�YATLARINI L�STELEME
SELECT DATE_,TOTALPRICE FROM ORDERS

--4-CITIES TABLOSUNDAK� HAN�G �EH�RLER�N OLDU�UNU TEKRARSIZ �EK�LDE L�STELEME
SELECT  CITY FROM CITIES

--5-ORDERDETAILS TABLOSUNDA TOPLAM KA� ADET �R�N S�PAR�� ED�LD���N� L�STELEME
SELECT COUNT(*)AMOUNT FROM ORDERDETAILS

--6-HER KULLANICININ TOPLAM �DEME M�KTARINI L�STELEME
SELECT
USERS.NAMESURNAME AS KULLANICI_�SM�,
SUM(PAYMENTS.PAYMENTTOTAL) AS TOPLAM_�DEME_M�KTARI
FROM USERS 
INNER JOIN ORDERS ON USERS.ID=ORDERS.USERID
INNER JOIN PAYMENTS ON PAYMENTS.ORDERID=ORDERS.ID
GROUP BY USERS.NAMESURNAME
ORDER BY SUM(PAYMENTS.PAYMENTTOTAL) DESC

--7-DISTRICT TABLOSUNDA HER �L�EYE BA�LI KA� KASABA OLDU�UNU L�STELEME




--8-COUNTR�ES TABLOSUNDAK� HER �LKEYE A�T OLAN �EH�RLER�N SAYISINI BULUN.
SELECT
COUNTRIES.COUNTRY AS �LKE,
COUNT(CITIES.CITY) AS �EH�R_SAYISI
FROM COUNTRIES
INNER JOIN CITIES ON CITIES.COUNTRYID=COUNTRIES.ID
GROUP BY COUNTRIES.COUNTRY
ORDER BY COUNT(CITIES.CITY)

--9-TOP 5 EN PAHALI �R�N�N ADI VE F�YATINI L�STELEME
SELECT TOP 5
ITEMNAME,UNITPRICE
FROM ITEMS
ORDER BY UNITPRICE DESC

--10-ORDERS TABLOSUNDA TOPLAM F�YATI 1000 �ZER�NDE OLAN S�PAR��LER�N DETAYLARINI L�STELEME
SELECT
ORDERS.TOTALPRICE AS TOPLAM_F�YAT,
ITEMS.ITEMNAME AS �R�N_�SM�
FROM ORDERS
INNER JOIN ORDERDETAILS O ON O.ORDERID=ORDERS.ID
INNER JOIN ITEMS ON O.ITEMID=ITEMS.ID
GROUP BY ITEMS.ITEMNAME,ORDERS.TOTALPRICE
HAVING ORDERS.TOTALPRICE>1000

--11 -T�M �R�NLER�N �S�MLER�N� TOPLAM SATI� M�KTARLARINI VE TOPLAM KAZAN�LARINI L�STELEME
select*from ORDERDETAILS
SELECT*FROM ITEMS
SELECT*FROM ORDERS



--13- USERS TABLOSUNDA EN FAZLA �DEME YAPAN K���Y� L�STELEME

SELECT TOP 1
USERS.NAMESURNAME AS �S�M,
SUM(PAYMENTS.PAYMENTTOTAL) AS TOPLAM_�DEME
FROM USERS
INNER JOIN ORDERS ON USERS.ID=ORDERS.USERID
INNER JOIN PAYMENTS  ON PAYMENTS.ORDERID=ORDERS.ID
GROUP BY USERS.NAMESURNAME
ORDER BY SUM(PAYMENTS.PAYMENTTOTAL) DESC

--14-PAYMENTS TABLOSUNDA EN D���K 3 �DEME M�KTARINI VE BU �DEMELER�N KULLANICILARINI L�STELEME
SELECT TOP 3
USERS.NAMESURNAME AS �S�M,
SUM(PAYMENTS.PAYMENTTOTAL) AS TOPLAM_�DEME
FROM USERS
INNER JOIN ORDERS ON USERS.ID=ORDERS.USERID
INNER JOIN PAYMENTS  ON PAYMENTS.ORDERID=ORDERS.ID
GROUP BY USERS.NAMESURNAME
ORDER BY SUM(PAYMENTS.PAYMENTTOTAL) ASC

--15-ORDERS TABLOSUNDAK� S�PAR��LER�N HANG� TAR�HTE VER�LD���N� VE VER�LEN TAR�HTEK� TOPLAM S�PAR�� SAYISI L�STELEME












--20-HER B�R KULLANICININ TOPLAM ALDI�I �R�N M�KTARINI VE TOPLAM KAZANCINI L�STELEME

SELECT 
USERS.NAMESURNAME AS KULLANICI_�SM�,
SUM(OD.AMOUNT) AS �R�N_M�KTAR�,
SUM(O.TOTALPRICE) AS TOPLAM_KAZAN�
FROM USERS
INNER JOIN ORDERS O ON USERS.ID=O.USERID
INNER JOIN ORDERDETAILS OD ON OD.ID=OD.ORDERID
GROUP BY USERS.NAMESURNAME
ORDER BY USERS.NAMESURNAME ASC